### ISSUE TITLE
Analysis tab for sketch editor

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-aeon-sketchbook#10]
Here, we can compute various results for a particular network sketch.

However, I'm not quite sure if this is the best course of action. These results would be invalid once the sketch changes, plus it does not make sense why these are all on one tab.

Maybe a better approach would be to have these analysis tools as separate "workflow windows"? 

Also, we should think about the ability to offload tasks to a separate machine (maybe even pause/resume?).

**Comment by ondrej33** [comment]
A prototype of an analysis workflow was added in #47. At the moment, there is an "analysis tab" at the initial window, which allows starting a new window for a particular analysis. This analysis workflow uses a "frozen" variant of the sketch, so the subsequent changes made in the editor do not invalidate the results. We can add some option to explicitly reload the sketch though.

At the moment, we only have a limited inference analysis (that processes a PSBN, basic regulations' properties and HCTL properties). It serves as a first step and a demonstration of the workflow. The user starts the inference with a button, a basic "wait" message appears, and once finished, a summary of results/computation appears. Users can then sample candidate networks. There is a button to restart the analysis.

We should as soon as possible:
- [ ] Extend the analysis to consider all parts of the sketch (generic static properties and template dynamic properties).
- [ ] Add consistency check at the beginning (#45).
- [ ] Implement the "static properties only" analysis or a different variant of (partial) inference to have at least two different (modular) working analyses. 
- [ ] Add some more advanced details about results (project number of candidates onto individual functions).
- [ ] Improve the UI of the inference.
- [ ] Handle the situation when there are no satisfactory candidates.

Further improvements could include a button for reloading the current version of the sketch from the editor, opening a new editor session with the candidate network, or allowing the user to select which properties to run inference with. But there is of course many more.

**Comment by ondrej33** [comment]
The inference workflow now supports all the necessary functionality for the initial release. There are some additional tasks that we could tackle in future:
- Add visualization of the results, perhaps through decision trees.
- Allow the user to select a subset of properties for the inference.
- Make the inference into a step-by-step iterative workflow, where intermediate results can be computed and then used for follow-up computations.

Another task is to extend the _Analysis tab_ with more types of analyses.
